openapi: "3.0.0"
info:
  description: "Rates API"
  version: "2.0.0"
  title: "Sswagger Rates API"
tags:
- name: "Rates API"
  description: "API For rates"
paths:
  
  /rate:
    post:
      tags:
        - Rates API
      summary: Post new rates
      description: |
        Retrieve payment methods and services, with dependencies between them
      operationId: validateBid
      requestBody:
        $ref: "#/components/requestBodies/RatesRequest"
      responses:
        "200":
          $ref: "#/components/responses/RateRequestResponse"

    get:
      tags:
        - Rates API
      summary: Get user rate for users requested times
      description: |
        By passing in the appropriate options, you can search for
        available user preferences in the system
      parameters:
        - in: query
          name: startDate
          required: true
          schema:
            type: string
            example: "2015-07-04T15:00:00+00:00"  
        - in: query
          name: endDate
          required: true
          schema:
            type: string
            example: "2015-07-04T20:00:00+00:00"
      responses:
        '200':
          description: rate for the time slot
          
          content:
            text/plain:
              schema:
                type: string
                example: "1000"
                
                
  /mertrics:
    get:
      summary: Get Performance Metrics
      tags:
        - Metrics API
      responses:
        '200':
          description: Metrics for mean time, max time and min time for a request to respond
          content:
            text/plain:
              schema:
                type: string
                
 
components:
  requestBodies:
  
    RatesRequest:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RatesRequest"
              
  responses:
    RateRequestResponse:
      description: "success"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/RatesRequest"
            
  schemas:

    RatesRequest:
      type: "object"
      required:
      - rates
      properties:
        rates:
          type: "array"
          items:
            allOf:
            - $ref: "#/components/schemas/RateParameters"
            
            
  
    RateParameters:
      type: "object"
      required: 
      - days
      - time
      - tz
      - price
      allOf:
      - $ref: "#/components/schemas/days"
      - $ref: "#/components/schemas/times"
      - $ref: "#/components/schemas/tz"
      - $ref: "#/components/schemas/price"

    days:
      type: "object"
      properties:
        days:
          type: "string"
          example: "mon,tues,wed,thurs,fri,sat,sun"
    times:
      type: "object"
      properties:
        times:
          type: "string"
          example: "0900-2200"
    tz:
      type: "object"
      properties:
        tz:
          type: "string"  
          example: "America/New_York"
    price:
      type: "object"
      properties:
        price:
          type: "integer"
          example: 1000
